### ISSUE TITLE
Installation Error on Ubuntu 14.04.5 LTS

### ISSUE THREAD

**Issue by spate141** [salestock/fastText.py#123]
Already tried following, same error both time!

> CC=/usr/bin/gcc-6 pip install -U fasttext
> CC=/usr/bin/clang-3.5 pip install -U fasttext

```
Collecting fasttext
  Using cached fasttext-0.8.3.tar.gz
    Complete output from command python setup.py egg_info:
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        except:
            raise Exception('fastText: Cannot load ' + filename +
                    ' due to C++ extension failed to allocate the memory')
    
        model_name = model.fm.modelName
        if model_name == 'skipgram' or model_name == 'cbow':
                     ^
    ------------------------------------------------------------
    
    fasttext/fasttext.pyx:158:18: Invalid types for '==' (string, str object)
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        except:
            raise Exception('fastText: Cannot load ' + filename +
                    ' due to C++ extension failed to allocate the memory')
    
        model_name = model.fm.modelName
        if model_name == 'skipgram' or model_name == 'cbow':
                                                 ^
    ------------------------------------------------------------
    
    fasttext/fasttext.pyx:158:46: Invalid types for '==' (string, str object)
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            # We build the dictionary here to support unicode characters
            for i in xrange(model.dict_nwords()):
                word = model.dict_get_word(i, encoding)
                words.append(word)
            return WordVectorModel(model, words, encoding)
        elif model_name == 'supervised':
                       ^
    ------------------------------------------------------------
    
    fasttext/fasttext.pyx:165:20: Invalid types for '==' (string, str object)
    Compiling fasttext/fasttext.pyx because it depends on /usr/local/lib/python2.7/dist-packages/Cython/Includes/libcpp/vector.pxd.
    [1/1] Cythonizing fasttext/fasttext.pyx
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Ax7hVZ/fasttext/setup.py", line 42, in <module>
        ext_modules = cythonize(extensions),
      File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 877, in cythonize
        cythonize_one(*args)
      File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 997, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: fasttext/fasttext.pyx
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Ax7hVZ/fasttext/
```

**Comment by spate141** [comment]
Nevermind, Issue solved with following: Uninstalling multiple cython packages!
```
pip uninstall Cython
pip uninstall cython
```
and then, 

```
pip install -U cython
pip install -U fasttext
```
