### ISSUE TITLE
install fasttext-to-f24a781 error,how to solve it?

### ISSUE THREAD

**Issue by baibaiw5** [salestock/fastText.py#134]
When i install fastText.py-feature-udpate-fasttext-to-f24a781 using command:
python setup.py install      
I got the follwing error:
-----------------------------------------------------
Compiling fasttext/fasttext.pyx because it depends on /data/anaconda2/envs/machine_learning2/lib/python2.7/site-packages/Cython/Includes/libcpp/vector.pxd.
[1/1] Cythonizing fasttext/fasttext.pyx
running install
running bdist_egg
running egg_info
writing requirements to fasttext.egg-info/requires.txt
writing fasttext.egg-info/PKG-INFO
writing top-level names to fasttext.egg-info/top_level.txt
writing dependency_links to fasttext.egg-info/dependency_links.txt
reading manifest file 'fasttext.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'facebookresearch-fastText-*'
no previously-included directories found matching '*.tar.gz'
writing manifest file 'fasttext.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'fasttext.fasttext' extension
error: unknown file type '.pxd' (from 'fasttext/interface.pxd')

**Comment by Omarito2412** [comment]
It worked for me when I ran
`make all`

**Comment by liuhe6** [comment]
get the same error

**Comment by bittlingmayer** [comment]
Same when installing with `pip install https://github.com/salestock/fastText.py/archive/feature/udpate-fasttext-to-f24a781.zip`.

`pip install -U Cython` did not help.

**Comment by mausch** [comment]
FWIW, I've tried running `docker run --rm -it -v $PWD:/work -w /work python:3.5 make` in that branch `udpate-fasttext-to-f24a781` to get the feature described in #139 and I got a few failed tests:

```
python test/skipgram_test.py --verbose
test_load_invalid_skipgram_model (__main__.TestSkipgramModel) ... ok
test_load_skipgram_model (__main__.TestSkipgramModel) ... ERROR
test_train_skipgram_model (__main__.TestSkipgramModel) ... ERROR
test_train_skipgram_model_default (__main__.TestSkipgramModel) ... ERROR

======================================================================
ERROR: test_load_skipgram_model (__main__.TestSkipgramModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/skipgram_test.py", line 23, in test_load_skipgram_model
    model = ft.load_model(skipgram_file, encoding='utf-8')
  File "fasttext/fasttext.pyx", line 159, in fasttext.fasttext.load_model (fasttext/fasttext.cpp:4031)
    raise ValueError('fastText: model name is not valid!')
ValueError: fastText: model name is not valid!

======================================================================
ERROR: test_train_skipgram_model (__main__.TestSkipgramModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/skipgram_test.py", line 94, in test_train_skipgram_model
    model = ft.skipgram(input_file, output, lr, dim, ws, epoch, min_count,
AttributeError: module 'fasttext' has no attribute 'skipgram'

======================================================================
ERROR: test_train_skipgram_model_default (__main__.TestSkipgramModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/skipgram_test.py", line 56, in test_train_skipgram_model_default
    model = ft.skipgram(input_file, output)
AttributeError: module 'fasttext' has no attribute 'skipgram'

----------------------------------------------------------------------
Ran 4 tests in 0.880s

FAILED (errors=3)
Makefile:59: recipe for target 'test-skipgram' failed
```
