### ISSUE TITLE
fastText: Cannot load ../fasttext/wiki.es/wiki.es.bin due to C++ extension failed to allocate the memory

### ISSUE THREAD

**Issue by smartinsightsfromdata** [salestock/fastText.py#148]
I'd like to re-open the issue as the problem appears still unsolved.

I've tried to run the code on an Azure VM with 16 vcpus, 112 GB memory.
I'm using anaconda python 3.6.

```
import fasttext
embeds = fasttext.load_model('./wiki.en.bin')
```

And I get the usual error:
```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
fasttext/fasttext.pyx in fasttext.fasttext.load_model()

MemoryError: std::bad_alloc

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-7-45b1af334f6e> in <module>()
----> 1 embeds = fasttext.load_model('./wiki.en.bin')

fasttext/fasttext.pyx in fasttext.fasttext.load_model()

Exception: fastText: Cannot load ./wiki.en.bin due to C++ extension failed to allocate the memory
```
Incidentally, I can load the model using gensim fasttext wrapper:
```
model = FastText.load_fasttext_format('./wiki.en.bin')
```

**Comment by adamleo** [comment]
Can anybody share some advice on this one?

I've experienced the same issue and surprising it has not been answered after 27 days.

The other related answers didn't really help.

**Comment by vgoklani** [comment]
In [1]: import fasttext

	In [2]: model_name = "lid.176.ftz"

	In [3]: model = fasttext.load_model(model_name)
	---------------------------------------------------------------------------
	RuntimeError                              Traceback (most recent call last)
	fasttext/fasttext.pyx in fasttext.fasttext.load_model (fasttext/fasttext.cpp:4236)()

	RuntimeError: vector

	During handling of the above exception, another exception occurred:

	Exception                                 Traceback (most recent call last)
	<ipython-input-3-c4228e324558> in <module>()
	----> 1 model = fasttext.load_model(model_name)

	fasttext/fasttext.pyx in fasttext.fasttext.load_model (fasttext/fasttext.cpp:4294)()

	Exception: fastText: Cannot load lid.176.ftz due to C++ extension failed to allocate the memory

**Comment by Ayman3mohamed** [comment]
same here 
 python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import fasttext
>>> model = fasttext.load_model('wiki.en.bin')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fasttext/fasttext.pyx", line 154, in fasttext.fasttext.load_model
Exception: fastText: Cannot load wiki.en.bin due to C++ extension failed to allocate the memory

**Comment by doannam020293** [comment]
same issue. Someone please give me solution!

**Comment by bung87** [comment]
related issue which closed 
 https://github.com/salestock/fastText.py/issues/115  

> This error is mainly because the wiki.en.bin file is trained with newer version of fastText, and as of 
  now you can't use current fastText.py python library to load/use newer models.

pyfasttext also has the same issue,

use the facebook official version is the right choise!

**Comment by tastyminerals** [comment]
@bung87 no, official version is only good for training and then printing the trained vectors to stdout. Binaries created by official version are unloadable as well :(

**Comment by harrypotter0** [comment]
@doannam020293  thanks for the advice, pyfasttext worked for me like a charm. Here is the script I used : 

```
import os
from pyfasttext import FastText

if __name__ == "__main__":
    file1 = open("fasttext_finance.txt","w")
    print("Loading the model")
    model_path = "/home/akash/Documents/nlp-tests/models/finance_model/faq.model.bin"
    model = FastText(model_path)

    lis = ["income","maturity","tax","mutual","fund","banks","cash","pf","epf","bankrupt",
            "loans","money","benefit","insurance","debt","advantage","sbi","kotak","shares",
            "food","hotel","retirement","travel","food","health","salary","account","advantage","disadvantage"]

    for word in lis:
        N = 50
        print("Most similar words to {} are :{}\n".format(word,model.nearest_neighbors(word, k=N)))
        file1.write("Most similar words to {} are :{}\n\n".format(word,model.nearest_neighbors(word, k=N)))
    file1.close()

```
