### ISSUE TITLE
TypeError: can't pickle fasttext_pybind.fasttext objects while trying to embed multiple words with multiprocessors

### ISSUE THREAD

**Issue by HomoSapienLCY** [salestock/fastText.py#177]
Hi,
First, thx for making fasttext available for the general public, it really makes my work much easier.

Recently I ran into a problem when trying to embed multiple words using multiprocessors, my code is:

```
class SentenceEmbedding:

    def __init__(self, idf_info, word_embed_model):
        self.num_docs = idf_info['num_docs']
        self.idf_vocab_dict = idf_info['idf_vocab_dict']
        self.idf_stopword_list = idf_info['idf_stopword_list']
        self.idf = idf_info['idf']
        self.word_embed_model = word_embed_model

    def embedWord(self, word, do_normalize):
        # fast text already returning a numpy array
        word_vec = self.word_embed_model[word]
        if do_normalize:
            word_vec = normalizeVector(word_vec)

        return word_vec

....

    # embed sentences with multicore
    def embedSentenceArrMP(self, sentences,
                           do_normalize_word=True, do_normalize_sentence=True,
                           default_IDF_weight=None):

        # use parallelism to speed up, use 1000 as chunk size
        with eval(core_pool_4) as pool:
            def runEmbed(s): return self.embedSentence(s,
                                                       do_normalize_word=do_normalize_word,
                                                       do_normalize_sentence=do_normalize_sentence,
                                                       default_IDF_weight=default_IDF_weight)
            sentence_vec_arr = pool.map(runEmbed, sentences)
            pool.close()
            pool.join()

        return sentence_vec_arr
```

In which, the core_pool_4 uses the multiprocessing.Pool to start 4 embedding processes at the same time, self.embedSentence call embedWord (there are multiple layers of function calls in the middle which not shown here), and embedWord embeds word by calling "word_embed_model" which is a fasttext model loaded through "fasttext_model = fasttext.load_model(model_bin)" .

The system throws me an error:
```
Traceback (most recent call last):
  File "embedding_sentence_processor.py", line 50, in <module>
    n_group_segment, default_IDF_weight=0)
  File "/home/liuchengyu/Documents/paper_writing_project/pdf-to-text_diy/python_utils/sentenceEmbeddingUtils.py", line 139, in embedSentenceArrMP
    default_IDF_weight=default_IDF_weight), sentences)
  File "/home/liuchengyu/anaconda3/envs/workspace/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/liuchengyu/anaconda3/envs/workspace/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/liuchengyu/anaconda3/envs/workspace/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/home/liuchengyu/anaconda3/envs/workspace/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/liuchengyu/anaconda3/envs/workspace/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle fasttext_pybind.fasttext objects
```

I have also try the pathos.multiprocessing.ProcessPool, it doesn't throw any error but just hang up forever...
Do anyone have experience or know how to run multiple fasttext processes in python in parallel? Would really appreciate it.

**Comment by multinucliated** [comment]
@HomoSapienLCY , I'm also getting the same error. You got any lead or solution?
