### ISSUE TITLE
Can't install on Ubuntu Sub Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by pakos47** [salestock/fastText.py#178]
Trying to install Fasttab is always resulting in this error....

Processing /home/noman/fastText
Requirement already satisfied: pybind11>=2.2 in /home/noman/anaconda3/lib/python3.6/site-packages (from fasttext==0.9.1) (2.3.0)
Requirement already satisfied: setuptools>=0.7.0 in /home/noman/anaconda3/lib/python3.6/site-packages (from fasttext==0.9.1) (41.0.1)
Requirement already satisfied: numpy in /home/noman/anaconda3/lib/python3.6/site-packages (from fasttext==0.9.1) (1.17.0)
Building wheels for collected packages: fasttext
  Building wheel for fasttext (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/noman/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_kzuedo7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_kzuedo7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-tgf3_5lx --python-tag cp36
       cwd: /tmp/pip-req-build-_kzuedo7/
  Complete output (58 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/fasttext
  copying python/fasttext_module/fasttext/FastText.py -> build/lib.linux-x86_64-3.6/fasttext
  copying python/fasttext_module/fasttext/__init__.py -> build/lib.linux-x86_64-3.6/fasttext
  creating build/lib.linux-x86_64-3.6/fasttext/util
  copying python/fasttext_module/fasttext/util/__init__.py -> build/lib.linux-x86_64-3.6/fasttext/util
  copying python/fasttext_module/fasttext/util/util.py -> build/lib.linux-x86_64-3.6/fasttext/util
  creating build/lib.linux-x86_64-3.6/fasttext/tests
  copying python/fasttext_module/fasttext/tests/__init__.py -> build/lib.linux-x86_64-3.6/fasttext/tests
  copying python/fasttext_module/fasttext/tests/test_configurations.py -> build/lib.linux-x86_64-3.6/fasttext/tests
  copying python/fasttext_module/fasttext/tests/test_script.py -> build/lib.linux-x86_64-3.6/fasttext/tests
  running build_ext
  creating tmp
  gcc -pthread -B /home/noman/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/noman/anaconda3/include/python3.6m -c /tmp/tmpwqc03wgv.cpp -o tmp/tmpwqc03wgv.o -std=c++14
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  gcc -pthread -B /home/noman/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/noman/anaconda3/include/python3.6m -c /tmp/tmpgh9swqdg.cpp -o tmp/tmpgh9swqdg.o -std=c++11
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  gcc -pthread -B /home/noman/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/noman/anaconda3/include/python3.6m -c /tmp/tmpjjphluyw.cpp -o tmp/tmpjjphluyw.o -std=c++0x
  gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-_kzuedo7/setup.py", line 202, in <module>
      zip_safe=False,
    File "/home/noman/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/noman/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/noman/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/noman/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/noman/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/home/noman/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/noman/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/noman/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/noman/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/noman/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/noman/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/home/noman/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/home/noman/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-req-build-_kzuedo7/setup.py", line 146, in build_extensions
      opts.append(cpp_flag(self.compiler))
    File "/tmp/pip-req-build-_kzuedo7/setup.py", line 109, in cpp_flag
      'Unsupported compiler -- at least C++0x support '
  RuntimeError: Unsupported compiler -- at least C++0x support is needed!
  ----------------------------------------
  ERROR: Failed building wheel for fasttext
  Running setup.py clean for fasttext
Failed to build fasttext
Installing collected packages: fasttext
  Running setup.py install for fasttext ... error
    ERROR: Command errored out with exit status 1:
     command: /home/noman/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_kzuedo7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_kzuedo7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kmlk8a7o/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-req-build-_kzuedo7/
    Complete output (59 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/fasttext
    copying python/fasttext_module/fasttext/FastText.py -> build/lib.linux-x86_64-3.6/fasttext
    copying python/fasttext_module/fasttext/__init__.py -> build/lib.linux-x86_64-3.6/fasttext
    creating build/lib.linux-x86_64-3.6/fasttext/util
    copying python/fasttext_module/fasttext/util/__init__.py -> build/lib.linux-x86_64-3.6/fasttext/util
    copying python/fasttext_module/fasttext/util/util.py -> build/lib.linux-x86_64-3.6/fasttext/util
    creating build/lib.linux-x86_64-3.6/fasttext/tests
    copying python/fasttext_module/fasttext/tests/__init__.py -> build/lib.linux-x86_64-3.6/fasttext/tests
    copying python/fasttext_module/fasttext/tests/test_configurations.py -> build/lib.linux-x86_64-3.6/fasttext/tests
    copying python/fasttext_module/fasttext/tests/test_script.py -> build/lib.linux-x86_64-3.6/fasttext/tests
    running build_ext
    gcc -pthread -B /home/noman/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/noman/anaconda3/include/python3.6m -c /tmp/tmptm9npftt.cpp -o tmp/tmptm9npftt.o -std=c++14
    gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    gcc -pthread -B /home/noman/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/noman/anaconda3/include/python3.6m -c /tmp/tmpl4i4yxwg.cpp -o tmp/tmpl4i4yxwg.o -std=c++11
    gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    gcc -pthread -B /home/noman/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/noman/anaconda3/include/python3.6m -c /tmp/tmptf6pm_7s.cpp -o tmp/tmptf6pm_7s.o -std=c++0x
    gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-_kzuedo7/setup.py", line 202, in <module>
        zip_safe=False,
      File "/home/noman/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/noman/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/noman/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/noman/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/noman/anaconda3/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/noman/anaconda3/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/noman/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/noman/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/noman/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/noman/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/noman/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/noman/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/home/noman/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/noman/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-req-build-_kzuedo7/setup.py", line 146, in build_extensions
        opts.append(cpp_flag(self.compiler))
      File "/tmp/pip-req-build-_kzuedo7/setup.py", line 109, in cpp_flag
        'Unsupported compiler -- at least C++0x support '
    RuntimeError: Unsupported compiler -- at least C++0x support is needed!
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/noman/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_kzuedo7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_kzuedo7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kmlk8a7o/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by pakos47** [comment]
had to install `build-essential` first..
SOLVED

**Comment by pakos47** [comment]
had to install `build-essential` first..
SOLVED
