### ISSUE TITLE
Pip installation failed

### ISSUE THREAD

**Issue by chsasank** [salestock/fastText.py#32]
On my mac (10.11) with conda environment python3, I have tried installing using 
```
$ pip install fasttext
```
which gives following error:

```
Collecting fasttext
  Using cached fasttext-0.6.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/z6/j4mcx1856ysgck57b7gb8fzc0000gq/T/pip-build-76pqyb4g/fasttext/setup.py", line 31, in <module>
        version=read_version(),
      File "/private/var/folders/z6/j4mcx1856ysgck57b7gb8fzc0000gq/T/pip-build-76pqyb4g/fasttext/setup.py", line 8, in read_version
        with open('fasttext/VERSION') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'fasttext/VERSION'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/z6/j4mcx1856ysgck57b7gb8fzc0000gq/T/pip-build-76pqyb4g/fasttext/
You are using pip version 8.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by pyk** [comment]
@chsasank ah sorry! `fasttext/VERSION` are missing in the package file. This should be fixed now, please run:

```shell
pip install --no-cache-dir -U fasttext
```
