### ISSUE TITLE
Support non utf-8 encoding

### ISSUE THREAD

**Issue by lefromage** [salestock/fastText.py#73]
facebook fasttext can use non-utf8 text codes in labels seemlesly, but this python layer cannot.
it would be nice to have any character support  implemented in the future
for now I cannot load the fasttext generated model : model = fasttext.load_model(model_bin)
I get this error

Traceback (most recent call last):
  File "/Users/xjxr170/PycharmProjects/keras/flask_fasttext1.py", line 25, in <module>
    model = fasttext.load_model(model_bin)
  File "fasttext/fasttext.pyx", line 172, in fasttext.fasttext.load_model (fasttext/fasttext.cpp:3982)
  File "fasttext/fasttext.pyx", line 43, in fasttext.fasttext.FastTextModelWrapper.dict_get_label (fasttext/fasttext.cpp:1526)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 37: invalid continuation byte

**Comment by pyk** [comment]
Hi @lefromage,

> facebook fasttext can use non-utf8 text codes in labels seemlesly, but this python layer cannot.

Yup currently, we only support UTF-8.

Maybe we can add `encoding` optional params in `load_model` to specify the non UTF-8 encoding like the following:

```python
model = fasttext.load_model('model.bin', encoding='utf-16')
```

What do you think?

**Comment by lefromage** [comment]
sure
