### ISSUE TITLE
Error on Fasttext

### ISSUE THREAD

**Issue by wakamd** [salestock/fastText.py#86]
I just installed the Fasttext package from https://pypi.python.org/pypi/fasttext. I then tried the example from the site:

import fasttext

# Skipgram model
model = fasttext.skipgram('data.txt', 'model')
print model.words # list of words in dictionary

# CBOW model
model = fasttext.cbow('data.txt', 'model')
print model.words # list of words in dictionary
I however got this error:

Traceback (most recent call last):
  File "C:/Python27/tryfasttext.py", line 1, in <module>
    import fasttext
ImportError: No module named fasttext
What could be the problem? How can I sort it out. N/B Am new to this deep learning stuff though. Am using python 2.7, on windows 10, 64 bit

**Comment by pyk** [comment]
Hi @wakamd ,

```
Traceback (most recent call last):
File "C:/Python27/tryfasttext.py", line 1, in 
import fasttext
ImportError: No module named fasttext
```

it means `fasttext` is not installed to your system yet. Please run:

```shell
pip install fasttext
```

**Comment by wakamd** [comment]
Just tried that but got this error: Failed building wheel for fasttext, then error: [Error2] The system cannot find the specified file

**Comment by wakamd** [comment]
C:\Users\Morris>pip install fasttext
Collecting fasttext
  Using cached fasttext-0.8.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy>=1 in c:\python27\lib\site-packages (from fasttext)
Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\lib\site-packages (from fasttext)
Building wheels for collected packages: fasttext
  Running setup.py bdist_wheel for fasttext
  Complete output from command c:\python27\python.exe -c "import setuptools;__file__='c:\\users\\morris\\appdata\\local\\temp\\pip-build-qgdjfs\\fasttext\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\morris\appdata\local\temp\tmpkjetl4pip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-2.7
  creating build\lib.win32-2.7\fasttext
  copying fasttext\model.py -> build\lib.win32-2.7\fasttext
  copying fasttext\__init__.py -> build\lib.win32-2.7\fasttext
  running build_ext
  building 'fasttext.fasttext' extension
  error: [Error 2] The system cannot find the file specified

  ----------------------------------------
  Failed building wheel for fasttext
Failed to build fasttext
Installing collected packages: fasttext
  Running setup.py install for fasttext
    Complete output from command c:\python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\morris\\appdata\\local\\temp\\pip-build-qgdjfs\\fasttext\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\morris\appdata\local\temp\pip-dicqbb-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building 'fasttext.fasttext' extension
    error: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\morris\\appdata\\local\\temp\\pip-build-qgdjfs\\fasttext\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\morris\appdata\local\temp\pip-dicqbb-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\morris\appdata\local\temp\pip-build-qgdjfs\fasttext

C:\Users\Morris>pip install -U --no-cache-dir fasttext
Collecting fasttext
  Downloading fasttext-0.8.0.tar.gz (72kB)
    100% |################################| 73kB 650kB/s
Requirement already up-to-date: numpy>=1 in c:\python27\lib\site-packages (from fasttext)
Requirement already up-to-date: future in c:\python27\lib\site-packages (from fasttext)
Installing collected packages: fasttext
  Running setup.py install for fasttext
    Complete output from command c:\python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\morris\\appdata\\local\\temp\\pip-build-x61zma\\fasttext\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\morris\appdata\local\temp\pip-4sisyo-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    creating build\lib.win32-2.7\fasttext
    copying fasttext\model.py -> build\lib.win32-2.7\fasttext
    copying fasttext\__init__.py -> build\lib.win32-2.7\fasttext
    running build_ext
    building 'fasttext.fasttext' extension
    error: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\morris\\appdata\\local\\temp\\pip-build-x61zma\\fasttext\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\morris\appdata\local\temp\pip-4sisyo-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\morris\appdata\local\temp\pip-build-x61zma\fasttext

**Comment by pyk** [comment]
@wakamd sorry, I can't reproduce your issue. I don't have windows env.

```
building 'fasttext.fasttext' extension
error: [Error 2] The system cannot find the file specified
```
However looking at the errors, your system dosn't have python dev lib to build the C++ extension (`python-dev` on Ubuntu).

**Comment by wakamd** [comment]
Hi I tried with Ubuntu after installing the required modules. Now I get this:
ValueError: fastText: cannot load data.txt. what data is used?
Regards

**Comment by pyk** [comment]
@wakamd from your code:

```
model = fasttext.skipgram('data.txt', 'model')
```

`data.txt` should be exists in the current directory

**Comment by weizier** [comment]
@pyk Thanks for your answer, but then I get an empty result when I do 'models.words' command although I can see some words in the 'model.vec' file. Could you help, thanks!

**Comment by Surtr86** [comment]
I am having the same problem. 
ValueError: fastText: cannot load data.txt.

Can someone explain to me how to make it work?

Iam using python 3.6 with anaconda on Windows 7.
Installed fasttext 0.8.3
